### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by girum89** [Rostlab/goPredSim#1]
Hello,

I was trying to test. But the file `seqvec_goa_2017.npz` (mentioned in config.txt as an example) is not found in the data directory. Could you please update or Suggest how to get/create that file.  Thanks.

**Comment by mariasche** [comment]
Hi, you can download the pre-computed embeddings from here: ftp://rostlab.org/goPredSim (As stated in the README). I updated the config to explicitly also state it in there.
