### ISSUE TITLE
How to generate custom embeddings

### ISSUE THREAD

**Issue by yunxiangfu2001** [Rostlab/goPredSim#2]
Hi, 
Thank you for your work and efforts. 
I'm currently doing a project on Pretrained Protein Language Models and would like to use goPredSim as one of the downstream evaluation tasks. Could you provide more details on how the CAFA3 target embeddings and GOA2017-2022 embeddings were generated (where to find the .fasta files, configurations for bio_embedding) so that we can generate custom embeddings?

Also is there a script to evaluate predictions?

**Comment by mariasche** [comment]
Hi,

you can now access the FASTA file for the targets in the `data/target_embeddings` folder. 
The FASTA files for the different GOA versions have been uploaded to the FTP server.

Also, here is a sample config that we used to generate SeqVec, ProtBert, and ProtT5 embeddings using the bio_embeddings pipeline. For more examples, I would refer you to the [bio_embeddings repo](https://github.com/sacdallago/bio_embeddings)

As an evaluation script, we used the publicly available [CAFA assessment tool](https://github.com/ashleyzhou972/CAFA_assessment_tool)
