### ISSUE TITLE
issues and fixes

### ISSUE THREAD

**Issue by rpkarandev** [Rostlab/goPredSim#4]
I had to make these corrections to successfully use goPredSim. I have compiled them below for your review. 

1) In file "function_prediction.py" > function "write_predictions_cafa", a section is indented left, resulting in "out_file not defined" error.

2) In file "embedding_lookup.py" > __init__  function, line "embedding = embedding_db[e][0]" leads to single value for lookup embeddings. I was using the ProtT5 embeddings FTP site.

changing "embedding = embedding_db[e][0]" to "embedding = embedding_db[e]" fixes it

3) In case, someone wondering how to create an embedding file, this worked for me.

with h5py.File( fileName, 'w') as f:
        for i, (name, e) in enumerate( zip( nameList, embeddings_protein ) ):
            e = e.reshape(1, -1)
            d = f.create_dataset( name, shape=e.shape, data=e  )
            d.attrs['original_id'] = mgId

I would appreciate it if developers could comment on it.

**Comment by t03i** [comment]
Thank you for your patience, we highly appreciate your suggestions and initiative. 

Indeed, point 1 is an oversight on our end and should be fixed now. 

Regarding point 2 and 3.:
If you skip the reshape step (and retain the dimensions of your per-protein embedding), goPredSim will work as is. 
goPredSim expects embedding files to be in the format proposed by [bio-embeddings](https://github.com/sacdallago/bio_embeddings) which retains the additional dimension to be consistent between per-protein and per-residue embeddings.
