### ISSUE TITLE
Cannot get pre-computed embeddings by ftp.

### ISSUE THREAD

**Issue by Lix1993** [Rostlab/goPredSim#6]
using filezilla:

Status:	Resolving address of rostlab.org
Status:	Connecting to 131.159.28.73:21...
Status:	Connection attempt failed with "ECONNREFUSED - Connection refused by server".
Error:	Could not connect to server

**Comment by Lix1993** [comment]
I found some file here:

https://rostlab.org/public/goPredSim/

![image](https://user-images.githubusercontent.com/12579295/234444647-9cc78def-1371-4311-8a9a-84adb6968b47.png)

**Comment by T1mK** [comment]
In general, our FTP is no longer online due to security concerns. 
Instead, we are now using HTTPS. Please trying going to 
https://rostlab.org/public/ for the files you are looking for.
