### ISSUE TITLE
Download Link in README.md is down

### ISSUE THREAD

**Issue by frapercan** [Rostlab/goPredSim#8]
### Problem Description

The download link for goPredSim precomputed files is down, which prevents access to the necessary resources to run the method as described in the provided documentation.

### Steps to Reproduce

1. Visit the URL: https://rostlab.org/public/goPredSim/
2. Notice that the site fails to load or returns an error.

### Comments
It seems that the necessary data might already be included in the data directory within the repository. Updating the documentation to reflect this could help prevent any confusion.

**Comment by t03i** [comment]
Thanks for reporting! The hardware hosting the files died a while back. 
We managed to recover the precomputed embeddings and uploaded them to Zenodo.
